### ISSUE TITLE
Deathrattles in version 1.5.0

### ISSUE THREAD

**Issue by Doomelf** [RedHatter/Graveyard#49]
Version 1.5.0 stopped tracking deathrattles.

**Comment by chWolfgang** [comment]
Personally, I have not had this issue. After the couple of patches for HS Deck Tracker, everything has been working fine.

Is it just Deathrattle minions not showing up? That only happens if you have a card that will RES deathrattle minions specifically. Make sure you have it turned on in the options. Maybe it got turned off?

**Comment by Doomelf** [comment]
I cannot speak for other things the plugin tracks, since I have not played with them after the upgrade to 1.5.0. I have been experimenting with a Big Spell Mage list and have enabled Dragoncaller Alanna and N'zoth in the plugin, but only deathrattle cards from N'zoth are not being tracked.

**Comment by Doomelf** [comment]
Nevermind, I figured out the problem. I was using the new version of N'zoth introduced in the latest patch instead of the one with Old Gods symbol. It was throwing the plugin off.

**Comment by Doomelf** [comment]
Nevermind, I figured out the problem. I was using the new version of N'zoth introduced in the latest patch instead of the one with Old Gods symbol. It was throwing the plugin off.
